server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

          default-filters:
            - JwtAuthenticationFilter

          routes:
            - id: resource-service
              uri: lb://api-resource
              predicates:
                - Path=/api/resource/**,/api/resource-group/**,/api/custom-field/**,/api/category-field/**,/api/timeslot/**
            - id: reservation-service
              uri: lb://api-reservation
              predicates:
                - Path=/api/reservation/**
            - id: statistics-service
              uri: lb://api-statistics
              predicates:
                - Path=/api/dashboard/**
            - id: queue-service
              uri: lb://api-queue
              predicates:
                - Path=/api/queues/**
            - id: websocket-route
              uri: lb://api-app
              predicates:
                - Path=/ws/**
            - id: main-service
              uri: lb://api-app
              predicates:
                - Path=/api/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000
  refresh-token-validity: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
