server:
  port: 8081

app:
  batch:
    viewcount:
      enabled: false

spring:
  application:
    name: api-resource


  # =================================================================
  # ?????? ??
  # =================================================================
  datasource:
    url: ${RESOURCE_DB_URL}
    username: ${RESOURCE_DB_USERNAME}
    password: ${RESOURCE_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  # =================================================================
  # JPA/Hibernate ??
  # =================================================================
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_OPTION:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect


  # =================================================================
  # Redis ??
  # =================================================================
  #    data:
  #      redis:
  #        host: ${REDIS_HOST}
  #        port: ${REDIS_PORT}
  #        password: ${REDIS_PASSWORD}


  # =================================================================
  # AWS ???? ?? (S3)
  # =================================================================
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${MY_BUCKET}
      region:
        static: ${AWS_REGION}


  # =================================================================
  # Spring Batch ?? ?? ?? ??
  # =================================================================
#    batch:
#      job:
#        enabled: false
#      jdbc:
#        initialize-schema: always


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: true
    fetchRegistry: true