spring:
  application:
    name: unibooker

  # =================================================================
  # ?????? ??
  # =================================================================
  datasource:
    url: ${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_OPTION}
    show-sql: true
    properties:
      hibernate:
        format_sql: true