apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: unibooker
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: linkverseunibooker/app:1
          ports:
            - containerPort: 8085
          envFrom:
            - configMapRef:
                name: backend-app-config
            - secretRef:
                name: backend-app-secret
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 110
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
