apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-queue-rollout
  namespace: unibooker
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: linkverseunibooker/queue:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: backend-queue-config
            - secretRef:
                name: backend-queue-secret
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 110
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
  strategy:
    blueGreen:
      activeService: backend-queue-service
      autoPromotionEnabled: true
      autoPromotionSeconds: 30