apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_PLACEHOLDER
      containers:
        - name: backend
          image: linkverseunibooker/backend:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
