server:
  port: 8082


# =================================================================
# 서킷 브레이커 설정
# =================================================================
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000    # TCP 연결하는데 기다리는 시간, 5초
        readTimeout: 5000       # HTTP로 데이터를 보내고 받는데 기다리는 시간, 5초

resilience4j:
  circuitbreaker:
    instances:
      B_API_CIRCUIT:
        # 서킷 브레이커의 상태
        # Closed : 정상적인 상태
        # Open : api-b가 일정 비율 이상으로 실패하거나 지연되면 "열림" 상태로 변경됨
        #         "열림" 상태에서는 서요청을 보내지 않고 즉시 실패 응답
        #         일정 시간이 지나면 "반열림" 상태로 전환
        # Half-Open : api-b에 요청을 전송하여 정상 동작 여부를 확인

        minimumNumberOfCalls: 5   # 최소 5개 이상의 요청이 있어야 실패율을 계산함
        slidingWindowSize: 10    # 최근 10의 요청 중
        failureRateThreshold: 50  # 50% 이상 실패하면 Open 상태로 변경
        waitDurationInOpenState: 30s  # Open 상태가 30초동안 유지, 30초 후 Half-Open상태로 전환
        permittedNumberOfCallsInHalfOpenState: 2  # Half-Open 상태에서 2번 성공하면 Closed 상태로 전환


spring:
  application:
    name: api-reservation

  # =================================================================
  # 데이터베이스 설정
  # =================================================================
  datasource:
    url: ${RESERVATION_DB_URL}
    username: ${RESERVATION_DB_USERNAME}
    password: ${RESERVATION_DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  # =================================================================
  # JPA/Hibernate 설정
  # =================================================================
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_OPTION:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # =================================================================
  # Kafka 설정 (신규 추가)
  # =================================================================
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    consumer:
      group-id: reservation-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000


  # =================================================================
  # AWS 클라우드 설정 (S3)
  # =================================================================
  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${MY_BUCKET}
      region:
        static: ${AWS_REGION}

  # =================================================================
  # Redis 설정
  # =================================================================
  data:
    redis:
      sentinel:
        master: ${REDIS_MASTER_NAME}
        nodes:
          - ${REDIS_SENTINEL_1}
          - ${REDIS_SENTINEL_2}
          - ${REDIS_SENTINEL_3}
      timeout: ${REDIS_TIMEOUT}

reservation:
  lock:
    wait-seconds: ${RESERVATION_WAIT:3}
    lease-seconds: ${RESERVATION_LEASE:15}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
    registerWithEureka: true
    fetchRegistry: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false