apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-resource
  namespace: unibooker
  labels:
    app: resource
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource
  template:
    metadata:
      labels:
        app: resource
    spec:
      containers:
        - name: resource
          image: linkverseunibooker/resource:4
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: backend-resource-config
            - secretRef:
                name: backend-resource-secret
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 110
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
