apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-reservation-rollout
  namespace: unibooker
  labels:
    app: reservation
  annotations:
    # Argo Image Updater 설정
    argocd-image-updater.argoproj.io/image-list: reservation=linkverseunibooker/reservation
    argocd-image-updater.argoproj.io/reservation.update-strategy: latest
    argocd-image-updater.argoproj.io/reservation.allow-tags: "latest"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: linkverseunibooker/reservation:latest   # latest 기준
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: backend-reservation-config
            - secretRef:
                name: backend-reservation-secret
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"

          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 110

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3

  strategy:
    blueGreen:               # Blue/Green 배포 방식
      activeService: backend-reservation
      previewService: backend-reservation-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 10
