apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-queue
  namespace: unibooker
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: linkverseunibooker/queue:1
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: backend-queue-config
            - secretRef:
                name: backend-queue-secret
          resources:
            limits:
              cpu: "500m"
              memory: "768Mi"
            requests:
              cpu: "250m"
              memory: "512Mi"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 110
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
