server:
  port: 8084

spring:
  application:
    name: api-statistics

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    registerWithEureka: true
    fetchRegistry: true