server:
  port: 8083

spring:
  application:
    name: api-queue

  datasource:
    url: none

  data:
    redis:
      sentinel:
        master: ${REDIS_MASTER_NAME}
        nodes:
          - ${REDIS_SENTINEL_1}
          - ${REDIS_SENTINEL_2}
          - ${REDIS_SENTINEL_3}
      timeout: ${REDIS_TIMEOUT:3000}

queue:
  scheduler:
    enabled: ${QUEUE_SCHEDULER_ENABLED:true}
    fixed-delay-ms: ${QUEUE_SCHEDULER_DELAY:10000}
    active-target-size: ${QUEUE_ACTIVE_TARGET_SIZE:150}
    max-promote-per-tick: ${QUEUE_PROMOTE_MAX:10}
    active-ttl-seconds: ${QUEUE_ACTIVE_TTL:120}
    resource-ids: ${QUEUE_RESOURCE_IDS:*}
    lock-key: ${QUEUE_LOCK_KEY:unibooker:queue:scheduler:lock}

management:
  endpoints.web.exposure.include: health,prometheus
  endpoint.health.probes.enabled: true
  endpoint.health.show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

# 스웨거 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: false  # ← UI는 Gateway에서만!